### PR TITLE
Performance tests for AMD's Bolt library

### PR DESCRIPTION
**Pull request by haahh**
This addresses issue https://github.com/kylelutz/compute/issues/220.

I've added:
* BOOST_COMPUTE_HAVE_BOLT option
* FindBolt.cmake cmake module from https://github.com/HSA-Libraries/Bolt
* Bolt perf tests (10):
 * bolt_accumulate (reduce)
 * bolt_count
 * bolt_exclusive_scan
 * bolt_fill
 * bolt_inner_product
 * bolt_max_element
 * bolt_merge
 * bolt_partial_sum (inclusive scan)
 * bolt_saxpy (transform)
 * bolt_sort
* Bolt perf tests in python benchmarking script perf.py
* Missing copyright and license info in one perf test

Bolt requires C++11, so performance tests for Bolt are build only if BOOST_COMPUTE_USE_CPP11 option is enabled. if BOOST_COMPUTE_HAVE_BOLT option is on and BOOST_COMPUTE_USE_CPP11 is off, warning message is printed.

If you're trying to test this PR and have problems with building Bolt on 64-bit Linux, contact me. I had the same problem.

### CODE REVIEW

**Comment by haahh** [comment]
Should I add Bolt benchmarks to perfdoc.py?

**Comment by kylelutz** [comment]
Yeah, if you could add it to `perfdoc.py` that would be great. Also, could you rebase this on the latest `develop` branch, it seems there may be a merge conflict. Thanks!

**Comment by haahh** [comment]
OK, it's done.

**Comment by kylelutz** [comment]
Looks great! Merged!

**Pull request merged**
