### PR TITLE
Add missing return to svm_ptr assignment operator

### PR DESCRIPTION
**Pull request by kylelutz**

### CODE REVIEW

**Comment by haahh** [comment]
I wonder if we need to find a stable POCL version (commit), use it instead of master branch because it became too unstable and just upgrade it from time to time after testing that new version is stable.

**Comment by kylelutz** [comment]
Yeah, I think that would be better and make the CI results more dependable. Would it make sense to stick to POCL releases or other tagged versions?

**Comment by haahh** [comment]
I'm not sure about releases (0.12 is 600 commits behind master,  0.13 - 200 commits behind) I will have to test them. If 0.13 works I'll use it, otherwise I'll just figure out the latest commit that works. I'll do on this on Saturday.

**Comment by kylelutz** [comment]
Sounds good to me, thanks!

**Pull request merged**
