### PR TITLE
add static asserts for device iterators

### LINKED ISSUE #392: Add static_assert for device iterators to all algorithms
Add `static_assert`'s for `is_device_iterator` to all algorithms which require device iterators. This will help prevent errors (or improve the error messages) when using these algorithms with host iterators.
##

### PR DESCRIPTION
**Pull request by lakshayg**
resolves #392

### CODE REVIEW

**Comment by lakshayg** [comment]
I grepped for DeviceIterator in the code and added BOOST_STATIC_ASSERTs at all the places. It is possible that I might have missed some places as I am not intimately familiar with the codebase. Please let me know if there are places I have missed.

**Comment by jszuppe** [comment]
Actually, you missed all the places (algorithm) it needs to be and added it to one place (algorithm) that doesn't need that (copy handles all 4 cases: device->host, host->device, device->device, host->host).

**Comment by jszuppe** [comment]
` BOOST_STATIC_ASSERT(is_device_iterator<Iterator>::value);` check would need to be added in all algorithms (except `copy`  or other if they already handle all cases) on the top level. For example:

```cpp
template<class InputIterator, class OutputIterator, class UnaryOperator>
inline OutputIterator transform(InputIterator first,
                                InputIterator last,
                                OutputIterator result,
                                UnaryOperator op,
                                command_queue &queue = system::default_queue())
{
    BOOST_STATIC_ASSERT(is_device_iterator<InputIterator>::value);
    BOOST_STATIC_ASSERT(is_device_iterator<OutputIterator>::value);
    return copy(
               ::boost::compute::make_transform_iterator(first, op),
               ::boost::compute::make_transform_iterator(last, op),
               result,
               queue
           );
}
```

**Comment by lakshayg** [comment]
@jszuppe I have made the changes, the patch is still incomplete and needs more work. Pushing it so that you can have a look and let me know if what I am doing is correct. Will add asserts to remaining algorithms once you review this.

**Comment by jszuppe** [comment]
Well, at the first glance, I'd say it looks ok. I'll review it later this week. However, before merging I need to resolve https://github.com/boostorg/compute/issues/764 in `develop` branch.

**Comment by lakshayg** [comment]
@jszuppe Sure, no problem. I have completed the patch from my side.

**Comment by jszuppe** [comment]
Please rebase on `develop`.

**Comment by lakshayg** [comment]
Done

**Comment by jszuppe** [comment]
In some places you removed `detail::is_buffer_iterator<BufferIterator>::value` in the 2nd commit, detail::is_device_iterator<BufferIterator>::value` wouldn't work there?

**Comment by lakshayg** [comment]
Done

**Pull request merged**
