### PR TITLE
Missing valarray operators

### PR DESCRIPTION
**Pull request by haahh**
This addresses issue https://github.com/boostorg/compute/issues/381.

I've implemented all missing valarray operators (see [valarray operators](http://www.cplusplus.com/reference/valarray/valarray/operators/)) and added tests for them.

Implemented operators work only for default context (queue) and are asynchronous.

Note that in OpenCL it's impossible to create memory buffer with bool type and because of that ```valarray<char>``` is used  as a return type for comparison and logical operators instead of ```valarray<bool>```.

### CODE REVIEW

**Comment by haahh** [comment]
I fixed some errors I did not encountered in my environment:
* empty macro argument (I did not run into this problem, cause by mistake I was compiling without ```-pedantic -Werror``` options.)
* 'bind' function call error (Somehow bind call works for me correctly without ::boost::compute::)

Now it seems that my valarray tests are to long :/

**Comment by haahh** [comment]
Travis build failed with ```No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.``` error.

On my system all 37 valarray tests work perfectly, both with g++4.8.2 and clang 3.4. I would be grateful if someone would confirm that.

**Comment by kylelutz** [comment]
I can confirm it passes locally on my laptop (Mac OSX, NVIDIA GPU, clang). The failure on Travis is strange, I wish the output had more information.

**Comment by kylelutz** [comment]
But it is good to see how comprehensive your tests are :-).

**Comment by haahh** [comment]
Thanks :-) I try to test all code I commit to Boost Compute.

My best guess now is that Travis was busy and somehow valarray tests were not completed before mentioned ten minutes passed.

**Comment by haahh** [comment]
I checked my code again and I saw I did not add static assert  in unary operators checking if valarray T type is a fundamental type. I will fix it tomorrow morning. (Of course it's not connected to Travis failure.)

**Comment by haahh** [comment]
I will check if the failure is caused by too many tests or some specific test freezes. I think running valarray tests with --log_level=all option would help find the problem, I'll try this when I get home. 

The only difference between my environment and that on Travis (apart from OpenCL drivers) is boost version - I have 1.55, Travis uses 1.48. Sadly I have some odd problems building this version, so I can't recreate exact same environment on my computer.

**Comment by haahh** [comment]
I located the problem - remainder binary operator test. This is [built with remainder binary operator test](https://travis-ci.org/boostorg/compute/jobs/62435729), which fails to complete valarray tests due to ```fatal error in "modulus_binary_operator": signal: integer divide by zero; address of failing instruction: 0x7f82a29a841b```, and this is [built without it](https://travis-ci.org/boostorg/compute/jobs/62435729), that works perfectly (I've temporally modified .travis.yml so it builds only valarray tests - it's faster that way). 

Still, I don't know why this problem occurs. I think test data is correct and IMO this test should work.

**Comment by kylelutz** [comment]
Looks great! Merged!

**Comment by haahh** [comment]
Thanks!

**Pull request merged**
