### PR TITLE
Added accessors to vector types

### PR DESCRIPTION
**Pull request by amirshavit**
This basically replaces the protected m_values member with public x/y, x/y/z/w, s0..s7, s0..sf members according to the vector size.

### CODE REVIEW

**Comment by haahh** [comment]
Is this approach safe? I mean, if I recall correctly a compiler can introduce a padding between two member variables. Of course I don't think that would happen in that case when using any popular C++ compiler for x86 like g++ or clang++, but it's still a question.

**Comment by amirshavit** [comment]
I don't think it's less safe than an array of scalars, but I'll try to find some text to support that.
Either way, a static assert of ```sizeof(Scalar) * N == sizeof(vector_type<Scalar, N>)``` can remove all concerns.

**Comment by haahh** [comment]
> I don't think it's less safe than an array of scalars, but I'll try to find some text to support that.

I am positive that a compiler can't put padding into an array of scalars.

> Either way, a static assert of sizeof(Scalar) * N == sizeof(vector_type<Scalar, N>) can remove all concerns.

:+1:

**Comment by jszuppe** [comment]
Done in #823

**Pull request closed without merging**
