### PR TITLE
Mt rng copy ctor spike

### PR DESCRIPTION
**Pull request by okdshin**
The copy ctor and assign op of compute::mersenne_twister_engine does not copy its states. So copied engine causes "Invalid Program" error.
This modification solves this problem.

### CODE REVIEW

**Comment by haahh** [comment]
Thanks! I think you should rebase your branch on the latest master revision.
25 gru 2015 18:53 "s.okada" <notifications@github.com> napisał(a):

**Comment by okdshin** [comment]
Sorry. I'll retry.

**Comment by haahh** [comment]
You can rebase and just force push your branch. You don't need to close
this pull request.
26 gru 2015 09:30 "s.okada" <notifications@github.com> napisał(a):

**Comment by okdshin** [comment]
OK. I'll not close next time. Sorry.
I fixed the branch and resent pull request.

**Pull request closed without merging**
