### PR TITLE
Add AppVeyor CI support

### PR DESCRIPTION
**Pull request by kylelutz**

### CODE REVIEW

**Comment by kylelutz** [comment]
Ahh, thanks for posting that. Hopefully we can figure out how to get their SDK to run on AppVeyor.

**Comment by ddemidov** [comment]
http://help.appveyor.com/discussions/suggestions/682-install-intel-opencl-code-builder

**Comment by haahh** [comment]
It's possible to build and use Khronos ICD (see https://github.com/clMathLibraries/clSPARSE) on AppVeyor CI and maybe even POCL (see https://github.com/pocl/pocl/blob/master/README.Windows). Are you sure Intel drivers can be used on AppVeyor?

**Comment by haahh** [comment]
I'm making progress with AppVeyor - see https://ci.appveyor.com/project/haahh/compute, but 1h build time limit does not seem to be enough for Boost.Compute + random tests fail (see https://ci.appveyor.com/project/haahh/compute/build/1.0.17 and https://ci.appveyor.com/project/haahh/compute/build/1.0.18).

**Pull request closed without merging**
