### PR TITLE
Fix compilation errors with GCC 8

### PR DESCRIPTION
**Pull request by 9prady9**

### CODE REVIEW

**Comment by 9prady9** [comment]
Some of the ci jobs failed but I don't think they are related to the changes I made. Any advice ?

**Comment by jszuppe** [comment]
Ahhh, maintaining OpenCL on Travis CI is a constant problem... I'll look into that.

**Comment by jszuppe** [comment]
"temporary server problem" on AMD website: https://community.amd.com/thread/227948

**Comment by jszuppe** [comment]
Thanks for the updates.

**Pull request merged**
