### PR TITLE
Temporary fix for Travis CI build

### PR DESCRIPTION
**Pull request by haahh**
See https://github.com/travis-ci/travis-ci/issues/5221.

### CODE REVIEW

**Comment by haahh** [comment]
Well, it didn't work.

**Comment by kylelutz** [comment]
That's unfortunate... I'm not sure what we should do with Travis-CI now that the new container-based infrastructure doesn't support OpenCL. I wonder if we should try with a different OpenCL implementation (maybe Intel or POCL)?

**Comment by ddemidov** [comment]
Did you guys look at https://drone.io/?

**Comment by ddemidov** [comment]
It does work, although the limit for a single job of 15 minutes is a bit tight: https://drone.io/github.com/ddemidov/vexcl/3.

**Comment by haahh** [comment]
Sorry for all those commits, but I'm trying to make it work on Trusty. When it works I'll make a proper squash.

**Comment by haahh** [comment]
Later this week I'll try using Intel OpenCL driver.

**Pull request closed without merging**
